# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3', '3.4']
    services:
      pinecone-database:
        image: ghcr.io/pinecone-io/pinecone-local:latest
        env:
          PORT: 5080
          PINECONE_HOST: localhost
        ports:
          - 5080:5080
        options: >-
          --health-cmd "curl -f http://localhost:5080/indexes || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      dense-index:
        image: ghcr.io/pinecone-io/pinecone-index:latest
        env:
          PORT: 5081
          INDEX_TYPE: serverless
          VECTOR_TYPE: dense
          DIMENSION: 2
          METRIC: cosine
        ports:
          - 5081:5081
        options: >-
          --health-cmd "curl -f http://localhost:5081/vectors/list || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      sparse-index:
        image: ghcr.io/pinecone-io/pinecone-index:latest
        env:
          PORT: 5082
          INDEX_TYPE: serverless
          VECTOR_TYPE: sparse
          DIMENSION: 0
          METRIC: dotproduct
        ports:
          - 5082:5082
        options: >-
          --health-cmd "curl -f http://localhost:5082/vectors/list || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
      # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    
    - name: Wait for Pinecone containers to be ready
      run: |
        echo "Waiting for Pinecone containers to be ready..."
        timeout 60 bash -c 'until curl -f http://localhost:5080/indexes; do echo "Waiting for database container..."; sleep 2; done'
        timeout 60 bash -c 'until curl -f http://localhost:5081/vectors/list; do echo "Waiting for dense index container..."; sleep 2; done'
        timeout 60 bash -c 'until curl -f http://localhost:5082/vectors/list; do echo "Waiting for sparse index container..."; sleep 2; done'
        echo "All Pinecone containers are ready!"
        
    - name: Run StandardRB Lint
      run: bundle exec standardrb
      
    - name: Run tests
      run: bundle exec rspec
